version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Code/WebApplication1/WebApplication1.sln" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore "Code/UnitTestProject1/UnitTestProject1.csproj"
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Code/WebApplication1/WebApplication1.sln" }}
      - run:
          name: "Restore nuget packages"
          command: nuget restore "Code/WebApplication1/WebApplication1.sln"
      - run:
          name: "Build with MSBuild"
          command: msbuild -t:Clean,Build -p:Configuration=Release "Code/UnitTestProject1/UnitTestProject1.csproj"
      - run:
          name: "Run Application Tests"
          command: |
            & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" Code/UnitTestProject1/bin/Release/UnitTestProject1.dll
      # - run:
          # name: "Print Working Directory"
          # command: pwd
      - store_artifacts:
          path: "Code/UnitTestProject1/bin/Release"
  build:
    description: Compile a release version of the app
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Code/WebApplication1/WebApplication1.sln" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore "Code/WebApplication1/WebApplication1.csproj"
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Code/WebApplication1/WebApplication1.sln" }}
      - run:
          name: "Restore nuget packages"
          command: nuget restore "Code/WebApplication1/WebApplication1.sln"
      - run:
          name: "Build with MSBuild"
          command: msbuild -t:Clean,Build -p:Configuration=Release "Code/WebApplication1/WebApplication1.csproj"
      - store_artifacts:
          path: "Code/WebApplication1/bin/Release"
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test